#!/bin/bash
###############################################################################
#                                                                             #
# prelim_enum,1.1a                                                            #
# by Scott Link (ath0)                                                        #
# I make no warranties or accept liability if you use this.                   #
# Copyright 2019                                                              #
# Released under Creative Commons (CC0) licensing.                            #
#                                                                             #
# 1.1a: Fixed version number, fixed nikto syntax                              #
# 1.2a: Spawn gobuster out, add spawning out full nmap                        #
# 1.3a: Fixed some missing -Pn flags for nmap                                 #
#                                                                             #
###############################################################################
	# Pass comma separated list of IP address to script for enumeration.
	# NO SPACES! E.g., prelim_enum 10.1.1.1,10.1.1.2,10.1.1.3

	# TODO
	#  - get mail

###############################################################################
#                                                                             #
# FUNCTION: enum_net                                                          #
#                                                                             #
###############################################################################
enum_net () {
		printf "Getting tftp/snmp info... (-sC will get OID entries, if string is public)\n"
		nmap -oA ${h}/${h}_initial_udp -sV -sC -sU -p 69,161,162 -Pn ${h} 2>&1>/dev/null
		printf "Running initial nmap...\n"
		nmap -oA ${h}/${h}_initial -sV -sC -Pn ${h} 2>&1>/dev/null
		printf "Spawing full nmap... (don't forget the power of ndiff...)\n"
		(nmap -oA ${h}/${h}_full -sV -sC -Pn -p- ${h} 2>&1>/dev/null) &
		printf "Getting the sploits...\n"
		searchsploit -v --nmap ${h}/${h}_initial.xml > ${h}/${h}.sploits
		
		# Let's get the articles...
		if [ ! -d ${h}/sploitdir ] ; then
			printf "I'm making the sploitdir...\n"
			mkdir ${h}/sploitdir 2>/dev/null
			if [ ${?} -ne 0 ] ; then
				printf "Fail in creating sploitdir!\n"
				printf "Exiting..."
				exit
			fi
		fi
	
		list=$(awk -F/ '{print $NF}' ${h}/${h}.sploits | grep -v "\-\-\-\-\-" \
			| grep -v Shellcodes | grep -v Papers | grep -v "^$" \
			| grep -v 'Exploit' | grep -v ")" | grep -v "xml" \
			| awk -F. '{print $1}' | sort -u)
		cd ${h}/sploitdir/
	
		printf "Time to get the articles...\n"

		for s in ${list} ; do
			searchsploit -m ${s} 2>&1>/dev/null
		done

		cd ..;cd ..
}

###############################################################################
#                                                                             #
# FUNCTION: enum_smb                                                          #
#                                                                             #
###############################################################################
enum_smb () {
	printf "Looking for SMB RCE vulns...\n"
	scripts="cve2009-3103 cve-2017-7494 ms06-025 ms07-029 ms07-029 ms08-067 ms10-054 ms10-061 ms17-010"
	portlist="139,445"

	for s in ${scripts} ; do 
		printf "Executing on ${s}\n"
		sleep 10
		nmap -v -p ${portlist} -oA ${h}/${s}.out -Pn -T3 --script=smb-vuln-${s} ${h} 2>&1>/dev/null
		enum4linux ${h} > ${h}/${enum4linux}.out
	done
}

###############################################################################
#                                                                             #
# FUNCTION: enum_web                                                          #
#                                                                             #
###############################################################################
enum_web () {
	portlist="80,8000,8080,443,8443"
	nmap -v -p ${portlist} -Pn -oA ${h}/${h}_http_test.out -T4 ${h}
	
	# Process gnmap file and kick off nikto scan
	results=$(grep Ports ${h}/${h}_http_test.out.gnmap | awk -F: '{print $3}' \
		| sed 's/ //g')
	
	for r in $(echo ${results} | sed 's/,/ /g') ; do
		testme=$(echo ${r} | awk -F/ '{print $2}')
		portnum=$(echo ${r} | awk -F/ '{print $1}')
	
		if [ ${testme} = open -a ${portnum} = 80 ] ; then
			printf "Scanning ${h} on port ${portnum}...\n"
			nikto -host ${h} -output ${h}/nikto.${h}.${portnum}.txt -Format txt 2>&1>/dev/null
			curl -o ${h}/${h}.${portnum}.index.html http://${h}:${portnum}
			(
				gobuster -u http://${h}:${portnum} -r \
					-w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt \
					-x php,txt -t 100 -l > ${h}/${h}-gobuster.${portnum} 2>/dev/null
			) &
		elif [ ${testme} = open -a ${portnum} = 8000 ] ; then
			printf "Scanning ${h} on port ${portnum}...\n"
			nikto -host ${h} -port ${portnum} -output ${h}/nikto.${h}.${portnum}.txt -Format txt 2>&1>/dev/null
			curl -o ${h}/${h}.${portnum}.index.html http://${h}:${portnum}
			(
				gobuster -u http://${h}:${portnum} -r \
					-w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt \
					-x php,txt -t 100 -l > ${h}/${h}-gobuster.${portnum} 2>/dev/null
			) &
		elif [ ${testme} = open -a ${portnum} = 8080 ] ; then
			printf "Scanning ${h} on port ${portnum}...\n"
			nikto -host ${h} -port ${portnum} -output ${h}/nikto.${h}.${portnum}.txt -Format txt 2>&1>/dev/null
			curl -o ${h}/${h}.${portnum}.index.html http://${h}:${portnum}
			(
				gobuster -u http://${h}:${portnum} -r \
					-w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt \
					-x php,txt -t 100 -l > ${h}/${h}-gobuster.${portnum} 2>/dev/null
			) &
		elif [ ${testme} = open -a ${portnum} = 443 ] ; then
			printf "Scanning ${h} on port ${portnum}...\n"
			nikto -host ${h} -ssl -port ${portnum} -output ${h}/nikto.${h}.${portnum}.txt -Format txt 2>&1>/dev/null
			curl -ssl -o ${h}/${h}.${portnum}.index.html https://${h}:${portnum}
			(
				gobuster -k -u https://${h}:${portnum} -r \
					-w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt \
					-x php,txt -t 100 -l > ${h}/${h}-gobuster.${portnum} 2>/dev/null
			) &
		elif [ ${testme} = open -a ${portnum} = 8443 ] ; then
			printf "Scanning ${h} on port ${portnum}...\n"
			nikto -host ${h} -ssl -port ${portnum} -output ${h}/nikto.${h}.${portnum}.out -Format txt 2>&1>/dev/null
			curl -ssl -o ${h}/${h}.${portnum}.index.html https://${h}:${portnum}
			(
				gobuster -k -u https://${h}:${portnum} -r \
					-w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt \
					-x php,txt -t 100 -l > ${h}/${h}-gobuster.${portnum} 2>/dev/null
			) &
		fi
			
	done
	
	printf "Done!\n"
}	

###############################################################################
#                                                                             #
# FUNCTION: make_dir                                                          #
#                                                                             #
###############################################################################
make_dir () {
	if [ ! -d ${h} ] ; then
		mkdir ${h} 2>/dev/null
	fi
}

###############################################################################
#                                                                             #
# FUNCTION: test_input                                                        #
#                                                                             #
###############################################################################
test_input () {
	if [ ! -n $1 ] ; then
		printf "You need pass comma separated list of IPs. Exiting...\n"
		exit
	fi

	iplist=$1
}

###############################################################################
#                                                                             #
# Main                                                                        #
#                                                                             #
###############################################################################

test_input $1

for h in $(echo ${iplist} | sed 's/,/ /g') ; do
	printf "I'm operating on ${h}\n"
	make_dir 
	enum_net
	enum_smb
	enum_web
done

